### ISSUE TITLE
หน้า Submit Job ของ User ช่อง Canceled

### ISSUE THREAD

**Issue by Tonzaly** [Team-BarbieBot-2023/mtnserviceth-front#13]
อยากให้ซ่อนแถว TECHNICIAN  และ Lv.  และ Complaint  เนื่องจากไม่ได้ใช้ เป็นการ ยกเลิกงานโดยแอดมินซึ่งจริงๆไม่ควร Complaint ได้
หมายเหตุ : ถ้าเป็นไปได้ถ้ายกเลิกงานอยากให้ใส่เหตุผลและให้เหตุผลที่ยกเลิกงานมาขึ้นที่ตาราง User ด้วยถ้าเป็นไปได้นะครับ เพราะตอนนี้จากที่ผมเทสใช้แอดมิน ยกเลิกงาน ฝั่ง User งานก็จะถูกย้ายไปที่ช่อง Canceled ซึ่ง User ไม่สามารถรู้ได้เลยว่าทำไมถึงโดนสั่งยกเลิกงานครับ

**Comment by developzego** [comment]
ตัดออกให้แล้วครับ
