### ISSUE TITLE
หน้า All Complaints ของ Administrator ช่อง ยังไม่ดำเนินการ

### ISSUE THREAD

**Issue by Tonzaly** [Team-BarbieBot-2023/mtnserviceth-front#16]
เหมือนจะบัคครับผมลองใส่ Description ว่า ทดสอบ1 และ result เลือกตักเตือน มันขึ้นว่า 
Failed to submit the form. ลองเลือกอื่นๆก็เป็นครับ มัน Errror ฝากเช็คด้วยนะครับน่าจะบัค

![Image](https://github.com/user-attachments/assets/b47261c4-7bcc-4694-8e73-31bd8fb5f115)
![Image](https://github.com/user-attachments/assets/69b46d62-6cbb-4f7c-8af2-868877be2645)

**Comment by developzego** [comment]
ลองเช็คส่วนชอง database connection ให้เพิ่ม code นี้ไปบรรทัดสุดท้าย

    multipleStatements: true
