### ISSUE TITLE
แก้คำ หน้า Jobs All ของ Administrator ให้นำหน้าตัวพิมพ์ใหญ่

### ISSUE THREAD

**Issue by Tonzaly** [Team-BarbieBot-2023/mtnserviceth-front#5]
pending เป็น Pending 
in progress เป็น In progress
completed เป็น Completed
canceled เป็น Canceled

แก้สีตรงจำนวน 
pending เป็น สีส้ม
in progress เป็น สีเหลือง
completed เป็น สีเขียว
canceled เป็น สีแดง

![Image](https://github.com/user-attachments/assets/63ee1850-0045-462d-886a-f046689a531a)

**Comment by developzego** [comment]
ปรับแก้ไขแล้วครับ
