### ISSUE TITLE
แก้ห น้า Jobs All ของ Administrator

### ISSUE THREAD

**Issue by Tonzaly** [Team-BarbieBot-2023/mtnserviceth-front#9]
ช่อง Completed และ Canceled ทั้งสองช่องมี จุด 3 จุดแต่พอกดเข้าไปขึ้นว่า No items. ซึ่งไม่สามารถใช้งานได้ อยากให้ซ่อนจุด 3 จุด ไปเลยเพราะว่าพอคลิกไปแล้วมันขึ้น No items. ไม่มีให้เลือกอยู่ดีถ้าซ่อนได้ให้ซ่อนนะครับผู้ใช้งานจะได้ไม่งงว่ามันไม่สามารถทำอะไรได้

![Image](https://github.com/user-attachments/assets/ffb96aa6-73b1-479e-ae1e-ea4fe3bc3a36)

**Comment by developzego** [comment]
ปรับไม่ให้แสดงแล้วครับ
